# MySQL Info
database.hostname: ""
database.port: 3306
database.name: ""
database.username: ""
database.password: ""

# Leveling Info
leveling.maxLevel: 3
leveling.minXP: 3
leveling.maxXP: 5

# Leveling Commands
leveling.level.1.command: "say {name} has leveled up to level 1!"
leveling.level.2.command: "say {name} has leveled up to level 2!"
leveling.level.3.command: "say {name} has leveled up to level 3"

# Leveling XP Needed
leveling.level.1.xp: 5
leveling.level.2.xp: 10
leveling.level.3.xp: 15

# Other Messages
message.xp.gained: "You have gained {xp} xp!"